FROM debian:10.3-slim
MAINTAINER Matt McCormick "matt.mccormick@kitware.com"

#include "common.debian"

#include "common.docker"

# Build-time metadata as defined at http://label-schema.org
# Note: To avoid systematic rebuild of dependent images, only
#       name and vcs-url are included.
ARG BUILD_DATE
ARG DOCKCROSS_ORG=dockcross
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
ARG DOCKCROSS_URL="https://github.com/${DOCKCROSS_ORG}/dockcross/blob/master/README.rst"

LABEL org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.description=$IMAGE \
      org.opencontainers.image.documentation=$DOCKCROSS_URL \
      org.opencontainers.image.licenses="SPDX-License-Identifier: MIT" \
      org.opencontainers.image.ref.name=$IMAGE \
      org.opencontainers.image.revision=$VCS_REF \
      org.opencontainers.image.source=$VCS_URL \
      org.opencontainers.image.title=$IMAGE \
      org.opencontainers.image.url=$DOCKCROSS_URL \
      org.opencontainers.image.vendor=$DOCKCROSS_ORG \
      org.opencontainers.image.version=$DOCKCROSS_VERSION
